---
title: "Apresentações"
description: |
  Material sobre apresentações que eu dei sobre temas envolvendo 
  finanças quantitativas, desenvolvimento quantitativo e data science.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 2022

- Palestra *Renda Fixa com R* @ [VI Seminário Internacional de Estatística com R](https://ser.uff.br/) &middot; [Repositório](https://github.com/eventoseroficial/Data_and_code/tree/main/Wilson%20Freitas) &middot; [Vídeo](https://youtu.be/eyd1VCAX864?t=9045)

## 2021

- Tutorial *Análise de Séries Temporais com Python* @ SciPy Latin America 2021 &middot; [Repositório](https://github.com/wilsonfreitas/scipyla-2021-tutorial-timeseries)

## 2018

- Importando e Manipulando Dados Financeiros no R @ SER II 2018 &middot; [Slides](https://wilsonfreitas.github.io/slides/ser-maio-2018/index.html)
- Modelagem de Séries Temporais com Python @ PythonSudeste 2018 &middot; [Slides](https://wilsonfreitas.github.io/slides/pythonsudeste-2018/index.html)

## 2017

- Modelagem de Séries Temporais em Python @ PyData &middot; [Slides](https://wilsonfreitas.github.io/slides/pydata-fevereiro-2017/index.html) &middot; [Repositório](https://github.com/wilsonfreitas/pydata-sp-2017-01) &middot; [Vídeo](https://www.youtube.com/watch?v=mo-ccIN4KOY)
- Modelagem de Séries Temporais em Python @ GrupySP &middot; [Slides](https://wilsonfreitas.github.io/slides/grupy-dezembro-2017/index.html) &middot; [Repositório](https://github.com/wilsonfreitas/grupysp-dezembro-2017)

## 2016
- Finanças Quantitativas com Python @ TDC &middot; [Slides](https://www.slideshare.net/wfreitas/finanas-quantitativas-com-python)
- APIs de visualização em Python @ GrupySP &middot; [Repositório](https://github.com/wilsonfreitas/grupysp-abril-2016)

## 2015
- bizdays: Dias Úteis em Qualquer Calendário @ GrupySP &middot; [Slides](https://wilsonfreitas.github.io/slides/grupy-julho-2015/index.html)
- Análise dos campeões da Corrida de São Silvestre com Python @ GrupySP &middot; [Slides](https://www.slideshare.net/wfreitas/analise-dos-campeoes-da-corrida-de-sao-silvestre-com-python)

## 2014
- APIs de visualização em Python @ TDC &middot; [Slides](https://www.slideshare.net/wfreitas/apis-de-visualizacao-em-python) &middot; [Vídeo](https://www.infoq.com/br/presentations/apis-de-visualizacao-em-python)
