---
title: "Gráficos de Composição de Índices da B3"
description: |
  Com o pacote {rb3} é possível obter a composição dos índices da B3, como o
  IBOVESPA, por exemplo.
  Vamos construir alguns gráficos para avaliarmos características da composição
  dos índices.
author:
  - name: Wilson Freitas
    url: {}
date: 2022-06-01
categories:
  - R
  - rb3
  - opendata
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r fig.height=7, fig.width=7}

library(rb3)
library(tidyverse)

top_weight <- function(.data, n = 10) {
    top_10 <- .data |>
        arrange(desc(weight)) |>
        slice_head(n = n) |>
        select(symbol, weight)
    total_weight <- sum(top_10$weight)
    others <- tibble(
        symbol = "Others",
        weight = 1 - total_weight
    )
    bind_rows(top_10, others) |>
        mutate(cum_weight = cumsum(weight))
}

index_name <- "IBXX"
g <- index_weights_get(index_name) |>
    top_weight() |>
    mutate(
        ymax = cum_weight,
        ymin = c(0, head(cum_weight, n = -1)),
        label_pos = (ymax + ymin) / 2,
        label = paste0(symbol, "\n", scales::percent(weight)),
        symbol = factor(symbol, ordered = TRUE)
    ) |>
    ggplot(aes(
        ymax = ymax, ymin = ymin,
        xmax = 4, xmin = 3,
        fill = symbol
    )) +
    geom_rect(colour = "white") +
    geom_label(
        x = 4.5, aes(y = label_pos, label = label), size = 3
    ) +
    annotate(
        "text",
        x = 0, y = 0, label = index_name, size = 16, colour = "grey",
        fontface = 2
    ) +
    coord_polar(theta = "y") +
    scale_fill_brewer(palette = "Set3") +
    scale_color_brewer(palette = "Set3") +
    xlim(c(0, 4)) +
    theme_void() +
    theme(legend.position = "none") +
    labs(
        caption = "Source: B3 (data imported using \U1F4E6 rb3) - wilsonfreitas"
    )

g
```